window.___browserSync___ = {};
window.___browserSync___.socketConfig = {
    reconnectionAttempts: 50,
    path: '/browser-sync/socket.io',
};
window.___browserSync___.socketUrl = '' + 'localhost:3000' + '/browser-sync'; // 固定
window.___browserSync___.options = {
    logLevel: 'info',
    plugins: [],
    port: 3000,
    snippetOptions: { async: true, whitelist: [], blacklist: [], rule: { match: {} } },
    reloadDebounce: 500,
    mode: 'server',
    scriptPaths: {
        path: '/browser-sync/browser-sync-client.js',
        versioned: '/browser-sync/browser-sync-client.js?v=2.26.7',
    },
    server: { baseDir: ['./'], serveStaticOptions: { index: 'index.html' } },
    logFileChanges: true,
    reloadThrottle: 0,
    clientEvents: [
        'scroll',
        'scroll:element',
        'input:text',
        'input:toggles',
        'form:submit',
        'form:reset',
        'click',
    ],
    urls: { local: 'http://localhost:3000', external: 'http://192.168.120.6:3000' },
    hostnameSuffix: false,
    scrollElements: [],
    scheme: 'http',
    startPath: null,
    single: false,
    host: null,
    codeSync: true,
    watchEvents: ['change'],
    browser: 'default',
    notify: true,
    open: false,
    reloadDelay: 0,
    minify: true,
    rewriteRules: [],
    injectFileTypes: ['css', 'png', 'jpg', 'jpeg', 'svg', 'gif', 'webp', 'map'],
    cors: false,
    proxy: false,
    tagNames: {
        jpg: 'img',
        css: 'link',
        svg: 'img',
        gif: 'img',
        jpeg: 'img',
        js: 'script',
        png: 'img',
        scss: 'link',
        less: 'link',
    },
    scrollRestoreTechnique: 'window.name',
    watch: false,
    watchOptions: {
        ignoreInitial: true,
        cwd: '/Users/yanxianliang/Desktop/workspace/electron-tools',
    },
    cwd: '/Users/yanxianliang/Desktop/workspace/electron-tools',
    logConnections: false,
    ghostMode: {
        clicks: true,
        scroll: true,
        location: true,
        forms: { submit: true, inputs: true, toggles: true },
    },
    middleware: [{ route: '', id: 'Browsersync Server ServeStatic Middleware - 0' }],
    ignore: [],
    injectChanges: true,
    excludedFileTypes: [
        'js',
        'css',
        'pdf',
        'map',
        'svg',
        'ico',
        'woff',
        'json',
        'eot',
        'ttf',
        'png',
        'jpg',
        'jpeg',
        'webp',
        'gif',
        'mp4',
        'mp3',
        '3gp',
        'ogg',
        'ogv',
        'webm',
        'm4a',
        'flv',
        'wmv',
        'avi',
        'swf',
        'scss',
    ],
    online: true,
    socket: {
        socketIoOptions: { log: false },
        socketIoClientConfig: { reconnectionAttempts: 50 },
        path: '/browser-sync/socket.io',
        clientPath: '/browser-sync',
        namespace: '/browser-sync',
        clients: { heartbeatTimeout: 5000 },
    },
    ui: { port: 3001 },
    logPrefix: 'Browsersync',
    scrollThrottle: 0,
    reloadOnRestart: false,
    localOnly: false,
    files: { core: { globs: [], objs: [] } },
    version: '2.26.7',
    logSnippet: true,
    injectNotification: false,
    snippet:
        '<script id="__bs_script__">//<![CDATA[\n    document.write("<script async src=\'/browser-sync/browser-sync-client.js?v=2.26.7\'><\\/script>".replace("HOST", location.hostname));\n//]]></script>\n',
    timestamps: true,
    serveStatic: [],
    scrollElementMapping: [],
    scrollProportionally: true,
    xip: false,
};

require('./src');
