// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    add: string;
    editSideDrawer: string;
    editSideMenu: string;
    editSideMenuWrapper: string;
    img: string;
    imgContentWrapper: string;
    imgWrapper: string;
    other: string;
    title: string;
}
export const cssExports: CssExports;
export default cssExports;
