// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    editStage: string;
    mobile: string;
    overlay: string;
    overlayElem: string;
}
export const cssExports: CssExports;
export default cssExports;
