// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    editContentWrapper: string;
    editLeftView: string;
    editRightView: string;
    editStageWrapper: string;
    editWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
